kind: ServiceAccount
apiVersion: v1
metadata:
  name: cptgpt-restart
  namespace: airflow-workers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cptgpt-restart
  namespace: cptgpt
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["cptgpt-local-ai"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cptgpt-restart
  namespace: cptgpt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cptgpt-restart
subjects:
  - kind: ServiceAccount
    name: cptgpt-restart
    namespace: airflow-workers